#!/usr/bin/env python3
"""
gen_dummy_input.py - generate a static standard-normal noise array for
timing/smoke-testing TFLM inference without a real MFCC front end.

Values are drawn from N(0,1) with a fixed seed, matching the statistics of a
globally z-score normalized MFCC window. Inference *time* does not depend on
input values, so this is valid for benchmarking; it is not valid for accuracy.

Usage:
    python3 gen_dummy_input.py 79 24 src/chewallow_dummy_input.h
    python3 gen_dummy_input.py 79 24 out.h --name g_chewallow_dummy_input
"""

import argparse
import os
import random
import shutil
from datetime import datetime

PER_LINE = 8


def main():
    ap = argparse.ArgumentParser(
        description="Generate a dummy float32 input header for TFLM benchmarking."
    )
    ap.add_argument("frames", type=int, help="time frames (e.g. 79)")
    ap.add_argument("coeffs", type=int, help="MFCC coefficients (e.g. 24)")
    ap.add_argument("header", help="output .h file")
    ap.add_argument(
        "--name",
        default="g_chewallow_dummy_input",
        help="C array name (default: g_chewallow_dummy_input)",
    )
    ap.add_argument(
        "--guard",
        default=None,
        help="include-guard macro (default: derived from output filename)",
    )
    ap.add_argument("--seed", type=int, default=1234, help="RNG seed (default: 1234)")
    ap.add_argument(
        "--no-backup", action="store_true", help="do not save a .bak of an existing file"
    )
    args = ap.parse_args()

    total = args.frames * args.coeffs
    guard = args.guard or (
        os.path.basename(args.header).replace(".", "_").replace("-", "_").upper()
    )

    rng = random.Random(args.seed)
    values = [rng.gauss(0.0, 1.0) for _ in range(total)]

    if os.path.exists(args.header) and not args.no_backup:
        backup = args.header + ".bak"
        shutil.copy2(args.header, backup)
        print(f"Backed up existing header -> {backup}")

    os.makedirs(os.path.dirname(os.path.abspath(args.header)), exist_ok=True)

    with open(args.header, "w") as out:
        out.write(f"#ifndef {guard}\n")
        out.write(f"#define {guard}\n")
        out.write("\n")
        out.write("// Generated by gen_dummy_input.py - do not edit by hand.\n")
        out.write("// Static standard-normal noise (mean 0, std 1), matching the shape\n")
        out.write("// and rough statistics of a real globally z-score normalized MFCC\n")
        out.write("// window. For timing only - not valid for accuracy testing.\n")
        out.write(f"// Shape:     ({args.frames}, {args.coeffs}) = {total} floats\n")
        out.write(f"// Seed:      {args.seed}\n")
        out.write(f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        out.write("\n")
        out.write(f"#define CHEWALLOW_DUMMY_FRAMES {args.frames}\n")
        out.write(f"#define CHEWALLOW_DUMMY_COEFFS {args.coeffs}\n")
        out.write(f"#define CHEWALLOW_DUMMY_LEN    {total}\n")
        out.write("\n")
        out.write(f"static const float {args.name}[{total}] = {{\n")

        for i in range(0, total, PER_LINE):
            chunk = values[i : i + PER_LINE]
            line = ", ".join(f"{v: .6f}f" for v in chunk)
            comma = "," if i + PER_LINE < total else ""
            out.write(f"    {line}{comma}\n")

        out.write("};\n")
        out.write("\n")
        out.write(f"#endif  // {guard}\n")

    print(f"Wrote {args.header}")
    print(f"  array: {args.name}[{total}]  ({args.frames} x {args.coeffs})")
    print(f"  guard: {guard}")


if __name__ == "__main__":
    main()
