#!/usr/bin/env python3
"""
tflite_to_header.py - convert a .tflite model into a TFLM-compatible C header.

Produces a header matching the structure TFLM requires:
  - alignas(16)  (TFLM's GetModel() fails on unaligned buffers)
  - const        (keeps the array in MRAM instead of RAM)
  - an explicit _len constant

Usage:
    python3 tflite_to_header.py model.tflite src/chewallow_model_data.h
    python3 tflite_to_header.py model.tflite out.h --name g_kws_model_data
    python3 tflite_to_header.py model.tflite out.h --no-backup
"""

import argparse
import os
import shutil
import sys
from datetime import datetime

BYTES_PER_LINE = 16


def verify_tflite(data, path):
    """TFLite flatbuffers carry the identifier 'TFL3' at offset 4."""
    if len(data) < 8:
        sys.exit(f"ERROR: {path} is only {len(data)} bytes - not a TFLite model.")
    magic = data[4:8]
    if magic != b"TFL3":
        sys.exit(
            f"ERROR: {path} does not look like a TFLite model.\n"
            f"       Expected b'TFL3' at offset 4, found {magic!r}.\n"
            f"       Did you pass a .h5 or SavedModel by mistake?"
        )


def main():
    ap = argparse.ArgumentParser(
        description="Convert a .tflite model into a TFLM-compatible C header."
    )
    ap.add_argument("tflite", help="input .tflite file")
    ap.add_argument("header", help="output .h file")
    ap.add_argument(
        "--name",
        default="g_chewallow_model_data",
        help="C array name (default: g_chewallow_model_data)",
    )
    ap.add_argument(
        "--guard",
        default=None,
        help="include-guard macro (default: derived from output filename)",
    )
    ap.add_argument(
        "--no-backup",
        action="store_true",
        help="do not save a .bak copy of an existing output file",
    )
    args = ap.parse_args()

    if not os.path.isfile(args.tflite):
        sys.exit(f"ERROR: input file not found: {args.tflite}")

    with open(args.tflite, "rb") as f:
        data = f.read()

    verify_tflite(data, args.tflite)

    guard = args.guard or (
        os.path.basename(args.header).replace(".", "_").replace("-", "_")
    )

    # Back up any existing header so a bad run is always recoverable.
    if os.path.exists(args.header) and not args.no_backup:
        backup = args.header + ".bak"
        shutil.copy2(args.header, backup)
        print(f"Backed up existing header -> {backup}")

    os.makedirs(os.path.dirname(os.path.abspath(args.header)), exist_ok=True)

    with open(args.header, "w") as out:
        out.write(f"#ifndef {guard}\n")
        out.write(f"#define {guard}\n")
        out.write("\n")
        out.write("// Generated by tflite_to_header.py - do not edit by hand.\n")
        out.write(f"// Source:    {os.path.basename(args.tflite)}\n")
        out.write(f"// Size:      {len(data)} bytes\n")
        out.write(f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        out.write("\n")
        out.write(f"alignas(16) const unsigned char {args.name}[] = {{\n")

        for i in range(0, len(data), BYTES_PER_LINE):
            chunk = data[i : i + BYTES_PER_LINE]
            line = ", ".join(f"0x{b:02x}" for b in chunk)
            comma = "," if i + BYTES_PER_LINE < len(data) else ""
            out.write(f"    {line}{comma}\n")

        out.write("};\n")
        out.write("\n")
        out.write(f"const unsigned int {args.name}_len = {len(data)};\n")
        out.write("\n")
        out.write(f"#endif  // {guard}\n")

    print(f"Wrote {args.header}")
    print(f"  array: {args.name}[{len(data)}]")
    print(f"  guard: {guard}")
    print(f"  model: {len(data)} bytes ({len(data)/1024:.1f} KB)")


if __name__ == "__main__":
    main()
