#!/usr/bin/env python3
"""
wav_to_header.py - embed a wav as a C array for the firmware MFCC self-test.

Feeds identical audio through the firmware and Python pipelines so the two
MFCC front ends can be compared directly, with no microphone or timing
variability in the way.

Usage:
    python3 wav_to_header.py clip.wav src/ww_test_audio.h
    python3 wav_to_header.py clip.wav out.h --name g_ww_test_audio
"""

import argparse
import os
import shutil
import sys
from datetime import datetime

import numpy as np
from scipy.io import wavfile

PER_LINE = 12
EXPECTED_RATE = 16000
EXPECTED_SAMPLES = 24000        # 1.5 s


def main():
    ap = argparse.ArgumentParser(
        description="Embed a wav as a C array for the firmware self-test.")
    ap.add_argument("wav", help="input wav (16 kHz mono int16)")
    ap.add_argument("header", help="output .h file")
    ap.add_argument("--name", default="g_ww_test_audio", help="C array name")
    ap.add_argument("--guard", default=None)
    ap.add_argument("--no-backup", action="store_true")
    args = ap.parse_args()

    rate, data = wavfile.read(args.wav)

    if rate != EXPECTED_RATE:
        sys.exit(f"ERROR: {args.wav} is {rate} Hz, expected {EXPECTED_RATE}")
    if data.ndim > 1:
        print(f"WARNING: {data.shape[1]} channels, taking channel 0")
        data = data[:, 0]
    if data.dtype != np.int16:
        sys.exit(f"ERROR: dtype is {data.dtype}, expected int16")

    n = len(data)
    if n != EXPECTED_SAMPLES:
        print(f"WARNING: {n} samples, expected {EXPECTED_SAMPLES} "
              f"({n/rate:.3f} s vs 1.500 s)")

    guard = args.guard or os.path.basename(args.header).replace(".", "_").upper()

    if os.path.exists(args.header) and not args.no_backup:
        shutil.copy2(args.header, args.header + ".bak")
        print(f"Backed up -> {args.header}.bak")

    os.makedirs(os.path.dirname(os.path.abspath(args.header)), exist_ok=True)

    with open(args.header, "w") as out:
        out.write(f"#ifndef {guard}\n#define {guard}\n\n")
        out.write("// Generated by wav_to_header.py - do not edit by hand.\n")
        out.write(f"// Source:    {os.path.basename(args.wav)}\n")
        out.write(f"// Samples:   {n} at {rate} Hz ({n/rate:.3f} s)\n")
        out.write(f"// Peak:      {int(np.abs(data).max())}\n")
        out.write(f"// RMS:       {float(np.sqrt(np.mean(data.astype(np.float64)**2))):.1f}\n")
        out.write(f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        out.write(f"#define WW_TEST_AUDIO_SAMPLES {n}\n\n")
        out.write(f"static const short {args.name}[{n}] = {{\n")

        for i in range(0, n, PER_LINE):
            chunk = data[i:i + PER_LINE]
            out.write("    " + ", ".join(f"{int(v):6d}" for v in chunk))
            out.write(",\n" if i + PER_LINE < n else "\n")

        out.write("};\n\n")
        out.write(f"#endif  // {guard}\n")

    print(f"Wrote {args.header}")
    print(f"  array   : {args.name}[{n}]")
    print(f"  peak    : {int(np.abs(data).max())}")
    print(f"  size    : {os.path.getsize(args.header)/1024:.0f} KB of source")


if __name__ == "__main__":
    main()
