#ifndef FAKE_OPUS_AUDIO_H
#define FAKE_OPUS_AUDIO_H

#include <stdint.h>

#define FAKE_OPUS_DURATION_SEC   30U
#define FAKE_OPUS_BITRATE_BPS    16000U
#define FAKE_OPUS_FRAME_MS       20U
#define FAKE_OPUS_TOTAL_BYTES    ((FAKE_OPUS_DURATION_SEC * FAKE_OPUS_BITRATE_BPS) / 8U)
#define FAKE_OPUS_FRAME_BYTES    ((FAKE_OPUS_BITRATE_BPS * FAKE_OPUS_FRAME_MS) / 8000U)
#define FAKE_OPUS_FRAME_COUNT    ((FAKE_OPUS_DURATION_SEC * 1000U) / FAKE_OPUS_FRAME_MS)

void FakeOpusAudioInit(void);
const uint8_t *FakeOpusAudioGetData(uint32_t *pLen);

#endif
